# Generated by Django 2.0.3 on 2018-05-01 03:24

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadesProyecto',
            fields=[
                ('id_actividades_entr', models.IntegerField(primary_key=True, serialize=False)),
                ('numero_actividad', models.IntegerField()),
                ('descripcion_actividades_proy', models.CharField(max_length=45)),
                ('alcance_actividades', models.CharField(max_length=45)),
                ('observaciones_actividades', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('numero_control', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('semestre', models.IntegerField()),
                ('nombre_alumno', models.CharField(max_length=45)),
                ('apellido_paterno_alumno', models.CharField(max_length=45)),
                ('apellido_materno_alumno', models.CharField(max_length=45)),
                ('actividades_alumno', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id_carrera', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_carrera', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CatMetasAlumno',
            fields=[
                ('id_cat_metas_alumno', models.IntegerField(primary_key=True, serialize=False)),
                ('descricpion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CatObserv',
            fields=[
                ('id_observaciones', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_observacion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='CatSancion',
            fields=[
                ('id_catalogo_sancion', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_catalogo_sancion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ColaboradorDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividades_colaborador', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Constancias',
            fields=[
                ('folio_constancia', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_constancia', models.DateField(verbose_name='fecha de constancia')),
                ('mensaje', models.CharField(max_length=45)),
                ('tipo_constancia', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Entregables',
            fields=[
                ('id_entregable', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_entregable', models.DateField(verbose_name='fecha de entregable')),
                ('observaciones_entregable', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoProyecto',
            fields=[
                ('id_estado_proyecto', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_estado_proy', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Etapas',
            fields=[
                ('id_etapa', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nombre_etapa', models.CharField(max_length=45)),
                ('fecha_inicio_etapa', models.DateField(verbose_name='fecha inicio de etapa')),
                ('fecha_fin_etapa', models.DateField(verbose_name='fecha fin de etapa')),
                ('meses', models.IntegerField()),
                ('descricpion_etapa', models.CharField(max_length=256)),
                ('metas', models.CharField(max_length=256)),
                ('actiidades_etapa', models.CharField(max_length=256)),
                ('productos', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Financiamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financ', models.BooleanField()),
                ('interno', models.BooleanField()),
                ('externo', models.BooleanField()),
                ('especificar', models.CharField(max_length=45)),
                ('infraestructura', models.DecimalField(decimal_places=2, max_digits=7)),
                ('consumibles', models.DecimalField(decimal_places=2, max_digits=7)),
                ('licencias', models.DecimalField(decimal_places=2, max_digits=7)),
                ('viaticos', models.DecimalField(decimal_places=2, max_digits=7)),
                ('publicaciones', models.DecimalField(decimal_places=2, max_digits=7)),
                ('equipo', models.DecimalField(decimal_places=2, max_digits=7)),
                ('patentes', models.DecimalField(decimal_places=2, max_digits=7)),
                ('otros', models.DecimalField(decimal_places=2, max_digits=7)),
                ('especifique', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='LineaInvestigacion',
            fields=[
                ('id_linea_investigacion', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_linea', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='LogrosConocimiento',
            fields=[
                ('id_logros_conocimiento', models.IntegerField(primary_key=True, serialize=False)),
                ('avances_conocimiento', models.CharField(max_length=45)),
                ('desarrollo_tecnologico', models.CharField(max_length=45)),
                ('infraestructura_tecnologica', models.CharField(max_length=45)),
                ('id_entregable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Entregables')),
            ],
        ),
        migrations.CreateModel(
            name='LogrosDivulgacion',
            fields=[
                ('id_logros_div', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo_articulo', models.CharField(max_length=45)),
                ('tipo_publicacion', models.CharField(max_length=45)),
                ('nombre_publicacion', models.CharField(max_length=45)),
                ('lugar', models.CharField(max_length=45)),
                ('fecha_logros_divulg', models.DateField(verbose_name='fecha devulgacion articulo')),
                ('id_entregable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Entregables')),
            ],
        ),
        migrations.CreateModel(
            name='LogrosPresentaciones',
            fields=[
                ('id_logros_present', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo_ponencia', models.CharField(max_length=45)),
                ('tipo_ponencia', models.CharField(max_length=45)),
                ('nombre_evento', models.CharField(max_length=45)),
                ('lugar', models.CharField(max_length=45)),
                ('fecha_logros_pres', models.DateField(verbose_name='fecha logros presentaciones')),
                ('id_entregable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Entregables')),
            ],
        ),
        migrations.CreateModel(
            name='LogrosRecursosHumanos',
            fields=[
                ('id_logros_rec_hum', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_trabajo', models.CharField(max_length=45)),
                ('categoria', models.CharField(max_length=45)),
                ('id_entregable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Entregables')),
            ],
        ),
        migrations.CreateModel(
            name='Metas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.BooleanField()),
                ('residencia', models.BooleanField()),
                ('tesis', models.BooleanField()),
                ('ponencia', models.BooleanField()),
                ('articulos', models.BooleanField()),
                ('libros', models.BooleanField()),
                ('propiedad_intelectual', models.CharField(max_length=255)),
                ('otros', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MetasAlcanzadas',
            fields=[
                ('id_metas_alcanzadas', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_metas_alcanzadas', models.CharField(max_length=45)),
                ('alcance_metas_alcanzadas', models.CharField(max_length=45)),
                ('observaciones_metas_alcanzadas', models.CharField(max_length=500)),
                ('id_entregable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Entregables')),
            ],
        ),
        migrations.CreateModel(
            name='MetasAlumnos',
            fields=[
                ('id_metas_alumno', models.IntegerField(primary_key=True, serialize=False)),
                ('descricpion_metas_alumno', models.CharField(max_length=256)),
                ('catalogo_metas_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.CatMetasAlumno')),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id_notificaciones', models.IntegerField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=45)),
                ('fecha_notificacion', models.DateField(verbose_name='fecha de notificacion')),
                ('estado_notificacion', models.BooleanField()),
                ('vista', models.DateField(verbose_name='fecha de vistas')),
            ],
        ),
        migrations.CreateModel(
            name='ObjetivosAlcanzados',
            fields=[
                ('id_objetivos_alcanzados', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_obj_alcanzados', models.CharField(max_length=45)),
                ('alcance_objetivos', models.CharField(max_length=45)),
                ('observaciones_obj_alcanzados', models.CharField(max_length=500)),
                ('id_entregable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Entregables')),
            ],
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones_gestion', models.CharField(max_length=1000)),
                ('observaciones_investigacion', models.CharField(max_length=1000)),
                ('observaciones_comite', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ObservacionesEntreg',
            fields=[
                ('id_observaciones_entreg', models.IntegerField(primary_key=True, serialize=False)),
                ('observaciones_entregable_ges', models.CharField(max_length=1000)),
                ('observaciones_entregable_inv', models.CharField(max_length=1000)),
                ('observaciones_entregable_com', models.CharField(max_length=1000)),
                ('id_observaciones', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.CatObserv')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('numero_personal', models.IntegerField()),
                ('sexo', models.CharField(max_length=1)),
                ('tipo_usuario', models.CharField(max_length=80)),
                ('grado_maximo_estudios', models.CharField(max_length=45)),
                ('telefono_movil', models.IntegerField(blank=True, null=True)),
                ('carrera', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Carrera')),
            ],
            options={
                'verbose_name': 'user',
                'abstract': False,
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Prorroga',
            fields=[
                ('id_prorroga', models.IntegerField(primary_key=True, serialize=False)),
                ('motivo', models.CharField(max_length=45)),
                ('tiempo', models.IntegerField()),
                ('observaciones_inv_gest', models.CharField(max_length=512)),
                ('observaciones_inv_pro', models.CharField(max_length=512)),
                ('observaciones_inv_com', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('folio_proyecto', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('fecha_presentacion', models.DateTimeField(verbose_name='fecha presentacion')),
                ('fecha_reactivacion', models.DateTimeField(verbose_name='fecha reactivacion')),
                ('palabra_clave1', models.CharField(max_length=45)),
                ('palabra_clave2', models.CharField(max_length=45)),
                ('palabra_clave3', models.CharField(max_length=45)),
                ('actividades_responsable', models.CharField(max_length=256)),
                ('convocatoris_CPR', models.CharField(max_length=45)),
                ('inicio', models.DateTimeField(verbose_name='fecha inicio')),
                ('fin', models.DateTimeField(verbose_name='fecha fin')),
                ('nombre_proyecto', models.CharField(max_length=45)),
                ('objetivo_general', models.CharField(max_length=45)),
                ('objetivo_especifico', models.CharField(max_length=45)),
                ('resultados', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='ProyectosCancelados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=45)),
                ('fecha_cancelacion', models.DateField(verbose_name='fecha cancelacion')),
                ('responsable_anterior', models.CharField(max_length=45)),
                ('folio_proyecto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id_solicitud', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_recepcion', models.DateField(verbose_name='fecha de recepcion')),
                ('nombre_recibio', models.CharField(max_length=45)),
                ('folio_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Resultados',
            fields=[
                ('id_resultados', models.IntegerField(primary_key=True, serialize=False)),
                ('resultados', models.CharField(max_length=45)),
                ('anexos', models.CharField(max_length=45)),
                ('id_entregable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Entregables')),
            ],
        ),
        migrations.CreateModel(
            name='ResumenEjecutivo',
            fields=[
                ('id_resumen_ej', models.IntegerField(primary_key=True, serialize=False)),
                ('resumen', models.CharField(max_length=45)),
                ('id_entregable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Entregables')),
            ],
        ),
        migrations.CreateModel(
            name='Sanciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_sancion', models.DateField(verbose_name='fecha de sancion')),
                ('folio_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Proyecto')),
                ('id_catalogo_sancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.CatSancion')),
                ('numero_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='TipoInvestigacion',
            fields=[
                ('id_tipo_investigacion', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_tipo_investigacion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TipoSector',
            fields=[
                ('id_tipo_sector', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion_sector', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Vinculacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_organizacion', models.CharField(max_length=45)),
                ('direccion', models.CharField(max_length=45)),
                ('area', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('nombre_completo_organ', models.CharField(max_length=45)),
                ('descripcion_organizacion', models.CharField(max_length=255)),
                ('descripcion_aportaciones', models.CharField(max_length=255)),
                ('folio_proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='prorroga',
            name='folio_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Proyecto'),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='folio_proyecto',
            field=models.ManyToManyField(blank=True, to='seguimientoProy.Proyecto'),
        ),
        migrations.AddField(
            model_name='observaciones',
            name='id_observaciones',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.CatObserv'),
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='receptor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Perfil'),
        ),
        migrations.AddField(
            model_name='metasalumnos',
            name='folio_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Proyecto'),
        ),
        migrations.AddField(
            model_name='metasalumnos',
            name='numero_control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Alumno'),
        ),
        migrations.AddField(
            model_name='metas',
            name='folio_proyecto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Proyecto'),
        ),
        migrations.AddField(
            model_name='financiamiento',
            name='folio_proyecto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Proyecto'),
        ),
        migrations.AddField(
            model_name='entregables',
            name='folio_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Proyecto'),
        ),
        migrations.AddField(
            model_name='entregables',
            name='id_etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Etapas'),
        ),
        migrations.AddField(
            model_name='constancias',
            name='folio_proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Proyecto'),
        ),
        migrations.AddField(
            model_name='constancias',
            name='id_etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Etapas'),
        ),
        migrations.AddField(
            model_name='colaboradordocente',
            name='folio_proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Proyecto'),
        ),
        migrations.AddField(
            model_name='colaboradordocente',
            name='numero_personal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Perfil'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='id_carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientoProy.Carrera'),
        ),
    ]
